#!/bin/bash

# Waits for emulator to completely boot to lock screen
# Used to run tests on Travis CI (#137)
# Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain
# Recommended by Travis docs - http://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator
# Source (under Apache 2.0) - https://github.com/andrewhr/rxjava-android-example/blob/master/ci/wait_for_emulator

set +e

bootanim=""
failcounter=0
timeout_in_sec=360

until [[ "$bootanim" =~ "stopped" ]]; do
  bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
  if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
    || "$bootanim" =~ "running" ]]; then
    let "failcounter += 1"
    echo "Waiting for emulator to start"
    if [[ $failcounter -gt timeout_in_sec ]]; then
      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
      exit 1
    fi
  fi
  sleep 1
done

echo "Emulator is ready"