/**
 * DO NOT MANUALLY EDIT THIS FILE
 *
 * This file is auto-generated by the build.gradle copyMapsApiV2Classes task based on the map
 * classes in the Google build flavor (src/google/java/org/onebusaway/android/map/googlemapsv2).
 * If you want to change something in this file, please edit the sources in
 * src/google/java/org/onebusaway/android/map/googlemapsv2 and rebuild the project.  Gradle will
 * detect that the files in the the Google build flavor changed and will re-generate the Amazon
 * build flavor map classes.  See Github Issues #158 and #254 for details.
 */

/*
 * Copyright (C) 2017 Rodrigo Carvalho (carvalhorr@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.onebusaway.android.map.googlemapsv2;

import com.amazon.geo.mapsv2.model.LatLng;
import com.amazon.geo.mapsv2.model.Marker;

/**
 *
 * Interface that each Overlayy needs to impement in order to be notified when a marker is clicked
 * or the map is clicked.
 */

public interface MarkerListeners {
    boolean  markerClicked(Marker marker);
    void removeMarkerClicked(LatLng latLng);
}
