/**
 * DO NOT MANUALLY EDIT THIS FILE
 *
 * This file is auto-generated by the build.gradle copyMapsApiV2Classes task based on the map
 * classes in the Google build flavor (src/google/java/org/onebusaway/android/map/googlemapsv2).
 * If you want to change something in this file, please edit the sources in
 * src/google/java/org/onebusaway/android/map/googlemapsv2 and rebuild the project.  Gradle will
 * detect that the files in the the Google build flavor changed and will re-generate the Amazon
 * build flavor map classes.  See Github Issues #158 and #254 for details.
 */

/*
 * Copyright (C) 2017 Rodrigo Carvalho (carvalhorr@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.onebusaway.android.map.googlemapsv2;

import com.amazon.geo.mapsv2.model.LatLng;
import com.amazon.geo.mapsv2.model.Marker;

/**
 * Interface that each Overlay needs to impement in order to be notified when a marker is clicked
 * or the map is clicked.
 */

public interface MarkerListeners {

    /**
     * Triggered when the user taps on a marker
     *
     * @param marker the marker the user tapped on
     * @return true if the listener has consumed the event (i.e., the default behavior should not
     * occur); false otherwise (i.e., the default behavior should occur). The default behavior is
     * for the camera to move to the marker and an info window to appear.  See
     * https://developers.google.com/android/reference/com/google/android/gms/maps/AmazonMap.OnMarkerClickListener
     */
    boolean markerClicked(Marker marker);

    /**
     * Triggered when the user taps on the map to hide a marker
     *
     * @param latLng the location on the map where the user tapped
     */
    void removeMarkerClicked(LatLng latLng);
}
